# Generated by Django 4.2.4 on 2023-09-26 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volgiadaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referee',
            name='username',
        ),
        migrations.AddField(
            model_name='referee',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
