# Generated by Django 4.2.4 on 2023-09-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maxPoints', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('timeSolved', models.DateTimeField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('solvedProblems', models.ManyToManyField(through='view.ProblemSolution', to='view.problem')),
            ],
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.team'),
        ),
    ]
